# Development Sandbox
version: "3.8"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD

  adminer:
    image: adminer
    restart: unless-stopped
    ports:
      - 8080:8080
