[package]
name = "discord-soundboard-bot"
version = "0.3.1-dev"
authors = ["Dominik Kus <dominik@kdtk.de>"]
edition = "2021"

[dependencies]
bigdecimal = "0.1"
diesel = { version = "1.4", default-features = false, features = ["postgres", "numeric"] }
diesel_migrations = "1.4"
dotenv = "0.15"
lazy_static = "1.4"
oauth2 = "4.2"
rand = "0.8"
regex = "1.5"
reqwest = { version = "0.11", features = ["json"] }
rocket = { version = "0.5.0-rc.2", features = ["secrets", "json"] }
rocket_sync_db_pools = { version = "0.1.0-rc.2", features = ["diesel_postgres_pool"] }
sanitize-filename = "0.4"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_with = "2.0"
serenity = { version = "0.11", features = ["cache", "standard_framework", "voice", "voice-model", "rustls_backend"] }
songbird = { version = "0.3" }
tokio = { version = "1.19", features = ["rt", "rt-multi-thread", "macros", "process"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
# Needed for Diesel Postgres linking for MUSL
# https://github.com/emk/rust-musl-builder#making-diesel-work
openssl = "*"