[package]
name = "discord-soundboard-bot"
version = "0.1.0"
authors = ["Dominik Kus <dominik@kdtk.de>"]
edition = "2018"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket.git"
default-features = false
features = ["json"]

[dependencies]
cached = "0.22"
lazy_static = "1.4"
rand = "0.8"
regex = "1"
sanitize-filename = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serenity = { version = "0.10", features = ["cache", "standard_framework", "voice", "voice-model", "rustls_backend"] }
songbird = { version = "0.1" }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros", "process"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
