[package]
name = "discord-soundboard-bot"
version = "0.2.0-dev"
authors = ["Dominik Kus <dominik@kdtk.de>"]
edition = "2018"

[dependencies.rocket]
git = "https://github.com/SergioBenitez/Rocket"
features = ["secrets"]

[dependencies.rocket_contrib]
git = "https://github.com/SergioBenitez/Rocket"
default-features = false
features = ["json", "helmet", "diesel_postgres_pool"]

[dependencies]
bigdecimal = "0.1"
diesel = { version = "1.4", default-features = false, features = ["postgres", "numeric"] }
diesel_migrations = "1.4"
dotenv = "0.15"
lazy_static = "1.4"
oauth2 = { git = "https://github.com/ramosbugs/oauth2-rs", branch = "main" }
rand = "0.8"
regex = "1"
reqwest = { version = "0.11", features = ["json"] }
sanitize-filename = "0.3"
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
serde_with = "1.6"
serenity = { version = "0.10", features = ["cache", "standard_framework", "voice", "voice-model", "rustls_backend"] }
songbird = { version = "0.1" }
tokio = { version = "1.0", features = ["rt", "rt-multi-thread", "macros", "process"] }
tracing = "0.1"
tracing-futures = "0.2"
tracing-subscriber = "0.2"
# Needed for Diesel Postgres linking for MUSL
# https://github.com/emk/rust-musl-builder#making-diesel-work
openssl = "*"